/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#283044",
        "tertiary-fixed": "#ffe088",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#ffb3b0",
        "tertiary-container": "#cba72f",
        "on-surface-variant": "#e3bebb",
        "outline-variant": "#5b403f",
        "on-tertiary-container": "#4e3d00",
        "on-tertiary-fixed": "#241a00",
        "on-primary": "#68000f",
        "primary": "#ffb3b0",
        "primary-fixed": "#ffdad8",
        "surface-container-high": "#222a3d",
        "surface-container-low": "#131b2e",
        "surface-container-lowest": "#060e20",
        "surface-container": "#171f33",
        "on-secondary-fixed": "#000767",
        "tertiary": "#e9c349",
        "error-container": "#93000a",
        "surface-tint": "#ffb3b0",
        "tertiary-fixed-dim": "#e9c349",
        "surface": "#0b1326",
        "on-primary-fixed": "#410006",
        "surface-container-highest": "#2d3449",
        "secondary": "#bdc2ff",
        "on-primary-fixed-variant": "#930019",
        "surface-dim": "#0b1326",
        "secondary-fixed": "#e0e0ff",
        "on-secondary-container": "#a8afff",
        "primary-container": "#be1e2d",
        "on-tertiary": "#3c2f00",
        "on-secondary": "#1b247f",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#343d96",
        "on-tertiary-fixed-variant": "#574500",
        "on-primary-container": "#ffd3d1",
        "background": "#0b1326",
        "outline": "#aa8987",
        "inverse-primary": "#b91a2a",
        "on-error": "#690005",
        "on-surface": "#dae2fd",
        "secondary-fixed-dim": "#bdc2ff",
        "on-background": "#dae2fd",
        "surface-variant": "#2d3449",
        "surface-bright": "#31394d",
        "secondary-container": "#343d96"
      },
      spacing: {
        "gutter": "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "base": "4px",
        "xs": "8px",
        "sm": "16px",
        "md": "24px",
        "lg": "40px",
        "xl": "64px",
      },
    },
  },
  plugins: [],
}
